- libproxy/modules/pxgsettings.cpp
ion recent versions of GLIB, it is mandatory to FIRST connect to the changed:: signal and then read values.
Without reading the values, it seems there is an initialization missing to start the change monitoring.
So: we now first connect the signal handler, directly followed by reading all the settings we care about.
> pxgsettings: g_signal_connect does not emmit changed signals

- libproxy/cmake/modules/config_kde.cmk
This is a follow-up to bd9bf72 ("Add generic KDE config module"): make
it possible for distributions to not build the KDE config module at all,
even if it does not have any dependencies on Qt/KDE/KF5.
> Make the KDE config module optional again.

- .travis.yml
Let's get some minimal travis tests in here
Things left to do:
* Decide which plugins we all want to test on Travis, install the build deps and enable the modules
Other than that, once I enable travis for /libproxy/libproxy, we at least get the PullReqs all tested as well.
Current test run: https://travis-ci.org/DimStar77/libproxy/builds/103157130
> travis-ci: add config file

- libproxy/test/get-pac-test.cpp
A small fix to make the library compile with CLang on MacOSX. This is due to inet_aton not being exposed when _POSIX_C_SOURCE is set..
> Fix compilation errors with CLang on MacOSX

- INSTALL
WITH_KDE4 no longer exists, and the KDE plugin now works with both KDE4
and KF5. Update the text in INSTALL to reflect those changes.
> INSTALL: update description of the WITH_KDE option.

- INSTALL
- bindings/perl/CMakeLists.txt
- bindings/perl/src/CMakeLists.txt
The Perl binding uses symbols from libperl.so, but since it is always
run after libperl.so itself is loaded, not linking against it does not
cause the problems that would normally occur.
Doing so was mandatory since 5077b75 ("bindings: perl: Do not link
against libperl"), which was catering for distros which install the
binding into vendor_perl and try not to rebuild all their Perl packages
on every Perl update. The flip-side is that it breaks things for other
groups: distros that install the binding into a versioned Perl
directory and allow different Perl versions to be installed
concurrently (for example, FreeBSD), or distros that pass
"--no-undefined" to the linker.
Provide an option, PERL_LINK_LIBPERL (whose default depends on the value
of PERL_VENDORINSTALL), to make the behavior …
> bindings: perl: Add an option to explicitly link against libperl.so.

- libproxy/modules/config_kde.cpp
- libproxy/modules/pacrunner_natus.cpp
- libproxy/modules/pacrunner_webkit.cpp
After finding out whether to use kreadconfig5 or kreadconfig,
it uses either qtpaths or kde4-config to determine the location
of the kioslaverc config file, to be able to notice modifications
that require a cache flush.
It's not the cleanest implementation due to kde4 support, but it should improve performance significantly to solve #16.
This also fixes several errors reported by cppcheck. (Not tested, but harmless)
> config_kde improvements

- bindings/python/libproxy.py
Annotate the return type of px_proxy_factory_new() to be void *, as otherwise
int is assumed. This works fine on 32-bit systems, where void * and int are the
same width, but is invalid on 64-bit (Linux) systems.
Additionally, annotate the argument type of free() and px_proxy_factory_free()
to be void * to match.
https://code.google.com/archive/p/libproxy/issues/146
> python: Avoid a crash on 64-bit systems

- libproxy/modules/ignore_ip.cpp
Qt5 started to use libproxy and this exposed a crashing bug on OpenBSD
when using Qt5 applications on Gnome 3.
Here's a sample backtrace:
https://gist.github.com/mulander/c03997ae7e3fe4e30af0d4f2ce2965f0
The issue is caused by an unguarded dereference of ign_ip.
Other parts of the code properly expect that sockaddr_from_string
might return null and guard against it.
Adding a proper guard prevents a segfault both in OpenBSD
www/otter-browser and devel/zeal.
> Fix #24 NULL pointer dereference in ignore_ip.cpp line 151

- libproxy/modules/config_kde.cpp
Apparently config_kde is like a magnet for regressions...
- Use std::map::find instead of map::at (issue #29)
- Add additional safety check
- Return as const ref
> Remove use of C++11 in config_kde module

- libproxy/modules/config_gnome3.cpp
This helps avoiding zombie processes in case a caller creates/destroys
ProxyFactories for each URL (even though we recommend to have a long-living
PF for caching reasons).
Originally reported at https://bugzilla.opensuse.org/show_bug.cgi?id=967601
> GNOME3: Wait for pxgsettings to vanish while destroying the plugin

- libproxy/test/get-pac-test.cpp
- libproxy/url.cpp
- libproxy/url.hpp
Adds a field for the query part to the URL object and parses and includes it in the request.
This addresses issue #38.
> Use the query string (parameters) when requesting PAC files

- cmake/FindMono.cmake
With mono 4.6, gmcs is no longer an upstream shipped wrapper.
Just fallback to 'mcs' if gmcs cannot be found. Distros still shipping
gmcs are assumed to know why they do so - in this case we favor their
local scripts.
Fixes issue #37.
> FindMono: fall back to mcs when gmcs cannot be found

- CMakeLists.txt
CMake 3.7 exports a "t" variable for all projects and because of that
the elseif statement in cmake/CMakeCSharpInformation.cmake:311 works
incorrectly if CMP0054 is not set to NEW (as "t" is expanded to the
variable value).
> Set CMP0054 CMake policy to NEW.

- libproxy/modules/pxgsettings.cpp
There are a few deprecation warnings with recent GLib versions, and a memory leak too.
> Fixes for pxgsettings

- libproxy/modules/network_networkmanager.cpp
StateChange signal has been deprecated since NM 0.7 and has been
completely removed in 0.9, see:
https://developer.gnome.org/NetworkManager/0.9/ref-migrating.html
Closes: #58
> Use StateChanged signal instead of StateChange

- libproxy/modules/wpad_dns_alias.cpp
It avoids the lasturl to be freed a 2nd time when the rewind() method is
called.
Closes: #59
> Set lasturl to NULL after free/delete

- libproxy/url.cpp
On Windows, sockets should be closed using closesocket() and not close(). Failing to do so results in:
1. A leak on older MSVC runtimes (or even closing an unrelated regular file)
2. A crash on newer versions
> Use closesocket() instead of close() on Windows

- libproxy/cmake/libproxy.cmk
- libproxy/libproxy.map
Preparation for https://github.com/libproxy/libproxy/pull/70, so that we can version new API being added
Any binary built against libproxy.so.1 before this was added, will keep on working (as long as we do only EXTEND the ABI, and not CHANGE)
Binaries built against the newer version of libproxy.so.1 will get additional information about the exported symbol name (i.e. LIBPROXY for the 'initial set', LIBPROXY_x_y_z for upcoming future APIs) - and will thus have proper dependencies too
> Add symbol versions - be ready to introduce new APIs as needed

- bindings/csharp/libproxy.cs
- bindings/perl/src/Libproxy.xs
- bindings/python/libproxy.py
- libproxy/libproxy.map
- libproxy/proxy.cpp
- libproxy/proxy.h
- samples/libcurl/curlget.c
- utils/proxy.c
Fixes issue #43.
Testcases still pass, but apparently they don't even use ```px_proxy_factory_get_proxies```...
```utils/proxy``` still works. I did not test any of the bindings and I'm also pretty sure that they're currently broken. I don't know how to fixup the bindings though, I never worked with any of those, especially vala.
> Add public px_proxy_factory_free_proxies function

- cmake/FindPython3Interp.cmake
Add 3.7 and 3.8 to the list of accepted Python 3 versions.
> python: support Python 3.7 and 3.8

- libproxy/modules/config_gnome3.cpp
> sigh
> 
> OK I now see why it was using /bin/sh to start the helper.
> 
> It's because the code is concatenate the gsettings keys to watch (in all_keys) as parameters
> 
> So this is not enough to just remove /bin/bash
> 
This reverts commit 8012bed4405efa31fffb57d6282de3e1513e4bd9.
> Revert "Do not invoke extra shell to run pxgsettings"

- libproxy/test/get-pac-test.cpp
get-pac-test.cpp:55:10: error: assigning to 'int' from incompatible type '__bind<int &, sockaddr *, unsigned int>'
ret = bind(m_sock, (sockaddr*)&addr, sizeof (struct sockaddr_in));                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> get-pac-test: Fix build with clang/libc++

- libproxy/modules/pacrunner_webkit.cpp
Delete memory allocated in jstr2str before return statements.
> Fix memory leak in functions 'dnsResolve' and 'webkit_pacrunner::run'

- cmake/FindPython3Interp.cmake
Add 3.9 to the list of accepted Python 3 versions.
> python: support Python 3.9

- libproxy/modules/pxgsettings.cpp
As it is a detailed signal, it only makes sense to append a :: when there is a specific property to target.
It used to be accepted but triggers a runtime warning with latest GLib.
> pxgsettings: use the correct syntax to connect to the changed signal

- libproxy/libproxy.map
Symbols other than px_* are still used by modules, so they have to be visible
as well. Unfortunately the version script can't deal with C++ classes properly,
it's not possible to match the vtable, typeinfo, etc. without resorting to the
platform specific mangling.
As a workaround, keep the default visibility of symbols which aren't explicitly
mentioned, this means that while users of private API wouldn't be caught
anymore, everything continues to work as usual, just with px_* being versioned.
This is an RFC as I'm not sure what happens to not explicitly mentioned symbols.
Maybe someone has an idea how this can be solved in a better way.
> RFC: Keep visibility of non-px_* symbols

- libproxy/cmake/modules.cmk
- libproxy/cmake/modules/config_pacrunner.cmk
- libproxy/modules/config_pacrunner.cpp
This is a new submission of the closed PR https://github.com/libproxy/libproxy/pull/35. Reading the discussion there, I've added a real `test()` function which tests whether the `org.pacrunner` name is owned on D-Bus (iow, whether pacrunner has already been started by some other entity). This test does not have the side effect to start pacrunner.
Note that NetworkManager has now functionality to update pacrunner's configuration when proxy settings are available for a NM connection (either via DHCP or similar, or by explicit configuration options). AFAICS, NetworkManager **starts** the pacrunner D-Bus service only when it's itself starting up. During connection activation, NM does not start the service.
Therefore, on "normal" Linux distributions, the test I implemented would only activate …
> New attempt to merge pacrunner support

- CMakeLists.txt
This commit fixes the following warning:
CMake Warning (dev) in CMakeLists.txt:
No project() command is present.  The top-level CMakeLists.txt file must
contain a literal, direct call to the project() command.  Add a line of
code such as
project(ProjectName)
near the top of the file, but after cmake_minimum_required().
CMake is pretending there is a "project(Project)" command on the first
line.
This warning is for project developers.  Use -Wno-dev to suppress it.
> cmake: fix generate-time warning

- libproxy/modules/config_gnome3.cpp
- libproxy/modules/pxgsettings.cpp
* gsettings: Always read at least the initial values of all keys
Previously, the gsettings (gnome3) module would wait until it had read
at least one key/value pair for each GSettings schema requested on the
command line. However, GSettings schemas often contain more than one
key. With a relatively elaborate proxy configuration, we don't
necessarily read all of them in one read() from the pipe, resulting in
the full configuration not being read until later - but for proxy(1),
"later" is too late, because it exits after the first query.
To resolve this, add a way for pxgsettings to signal that it has
written all the initial values (a blank line), and wait for that.
Fixes: #116
* gsettings: Wait for all configuration updates
If we haven't polled the pxgsettings helper for a while, there …
> Fix race conditions in GSettings backend

- libproxy/modules/pacrunner_mozjs.cpp
If we don't assign the temporary std::string returned by
url_.to_string() to a variable, then it immediately goes out of scope
and is freed, resulting in the result of c_str() pointing into freed
memory. This works about as well as you would expect.
Fixes: #119
> mozjs: Avoid use-after-free

- utils/proxy.c
It's not needed here and has been deprecated for a long time. Fixes:
[ 82%] Building CXX object libproxy/CMakeFiles/config_kde.dir/modules/config_kde.cpp.o
In file included from /usr/include/bits/libc-header-start.h:33,
from /usr/include/stdio.h:27,
from /home/mcatanzaro/Projects/libproxy/utils/proxy.c:21:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
|   ^~~~~~~
> Stop defining _BSD_SOURCE

- libproxy/modules/config_w32reg.cpp
Converts the windows registry bypass list from semi-colon delimited to comma delimited
Returns the full comma-delimited list of bypass urls.
This should address an open issue https://github.com/libproxy/libproxy/issues/96
> Parse the windows bypass list

- libproxy/extension_config.hpp
- libproxy/extension_pacrunner.cpp
- libproxy/extension_pacrunner.hpp
- libproxy/modules/config_envvar.cpp
- libproxy/modules/config_gnome.cpp
- libproxy/modules/config_gnome3.cpp
- libproxy/modules/config_kde.cpp
- libproxy/modules/config_macosx.cpp
- libproxy/modules/config_pacrunner.cpp
- libproxy/modules/config_sysconfig.cpp
- libproxy/modules/config_w32reg.cpp
- libproxy/modules/pacrunner_mozjs.cpp
- libproxy/modules/pacrunner_natus.cpp
- libproxy/modules/pacrunner_webkit.cpp
- libproxy/url.cpp
- libproxy/url.hpp
C++98 called and it wants its dynamic exception specifications back!
We'd better comply.
https://en.cppreference.com/w/cpp/language/except_spec
Fixes #127
> Remove dynamic exception specifications

- .gitignore
- libproxy/modules/config_kde.cpp
- libproxy/url.cpp
With improved CMake support in Visual Studio 2019 I can successfully compile in Visual Studio using Ninja as the generator and MSVC. However, this required some small changes in the source code.
The change was necessary in order to enable `config_kde.cpp` to successfully compile. This was accomplished by defining WIN32 only macros for the `popen` and `pclose` methods from `unistd.h` to point to the windows `_popen` and `_pclose` functions in `stdio.h`.  While these are not 1 : 1 equivalents, for the use here they are functionally equivalent. I followed a similar pattern implemented in the `url.cpp` file found here: https://github.com/libproxy/libproxy/blob/d6990f4aaab4b947a490ab1abfd9ac6e62d66d7a/libproxy/url.cpp#L23
While examining the solution in `url.cpp`, I noticed that there was some …
> Enable building in Visual Studio 2019 without mingw.

- libproxy/proxy.cpp
Using the wrong delete operator is undefined behavior.
All this manual new/delete really ought to be replaced by
std::unique_ptr, but this will suffice for now.
> Fix mismatched new[]/delete[] in proxy.cpp

- CMakeLists.txt
I was very surprised to discover that libmodman is a system library.
It's packaged separately from libproxy in distros (I checked Fedora and
openSUSE), and libproxy's build system does not install its files, but
libproxy nonetheless appears to be the only upstream. Distros build the
system library from a decade-old tarball.
Anyway, nothing besides libproxy uses it, so the system package should
probably be retired. By using our own internal libmodman, we can make
API and ABI changes to modernize libmodman and improve its safety,
without having to worry about other consumers (which don't exist,
anyway).
> Never use system libmodman

- libproxy/extension_pacrunner.cpp
- libproxy/extension_pacrunner.hpp
- libproxy/proxy.cpp
libproxy currently attempts to cache pacrunner objects in the pr member
variable of its pacrunner_extension object. This is broken, though,
because it relies on the pacrunner object also being stored in
pacrunner_extension's last member variable, which is never written to.
So that caching has never worked properly. In practice, it only does one
thing: it causes a threadsafety bug, #68, because it causes the old
pacrunner object to be deleted on the thread that is creating the new
pacrunner, which is illegal for both the mozjs and WebKit-based
pacrunner extensions that expect their objects to be deleted on the same
thread they were created on.
This patch was originally written by Dan Winship for Fedora 19. It got
dropped in Fedora 24, then resurrected again for Fedora 28 after we
noticed …
> Remove nonfunctional and crashy pacrunner caching

- libproxy/url.cpp
The bug was found on Windows 10 (MINGW64) when PAC is enabled. It turned
out to be the large PAC file (more than 102400 bytes) returned by a
local proxy program with no content-length present.
> Fix buffer overflow when PAC is enabled

- NEWS
- libproxy/CMakeLists.txt
Let's prepare a 0.4.16 release; enough stuff accumulated to justify this release finally
Then we should work on 0.5, which should revive the dbusify branch
> Release: 0.4.16

- bindings/python/libproxy.py
> python bindings: fix "TypeError: _argtypes_ must be a sequence of types"

- bindings/python/libproxy.py
This is not needed since the addition of px_proxy_factory_free_proxies()
in d52cc34458b1d6a524df12db2671fa3a15892fcf
> python: Do not load the libc anymore

- bindings/python/python2/CMakeLists.txt
- bindings/python/python3/CMakeLists.txt
- cmake/FindPython3Interp.cmake
As suggested by Miro Hrončok, change the way that the Python interpreter
version is found. Additionally, update the static list of accepted
Python 3 versions.
https://bugzilla.redhat.com/show_bug.cgi?id=1898060
I am guessing that it would be simpler to use the newer FindPython3 functionality in CMake 3.12 and above, but I do not know much about CMake, sorry!
> python: Support Python 3.10 and above

- cmake/FindPython2Interp.cmake
- cmake/FindPython3Interp.cmake
These were copied from CMake and the license says their blurb should be
replaced with the full text of the license, so let's do that.
Note that the original copyright file is here:
https://github.com/Kitware/CMake/blob/ea28d28a6169b0431407f97403b3ac406997e153/Copyright.txt
and that's what I've copied this from.
> Fix license of FindPython[2,3]Interp.cmake

- libproxy/modules/config_kde.cpp
`qtpaths` is a developer tool which is not guaranteed to exist on all KDE installations (notably KDE neon).  If it doesn't exist, the cache isn't used at all.
The equivalent to `kde4-config` is `kf5-config`, let's use that.
See also https://bugs.kde.org/show_bug.cgi?id=445813#c2
I think the proper way would be to make this module use D-Bus instead of calling `kreadconfig5` over and over again. But this is a quick fix without which the whole caching stuff is useless for the average user.
> config_kde: Use kf5-config instead of qtpaths

- libproxy/modules/config_gnome3.cpp
Only GNOME3 is affected since support for Wayland begins at 3.2.0.
> Add gnome-wayland to permitted DESKTOP_SESSION

- libproxy/url.cpp
The request header in get_pac() currently misses the host port and thus breaks
every proxy running on another port. See https://gitlab.gnome.org/GNOME/glib-networking/-/issues/138 for example.
Add this missing port in case it is not http default port 80.
> Add host port to request header

- bindings/perl/lib/CMakeLists.txt
- bindings/perl/src/CMakeLists.txt
- bindings/perl/t/CMakeLists.txt
The module files for testing were installed in the wrong location and blib
wasn't even enabled. Fix the location and use plain PERL5LIB.
Hook it up to ctest by using add_test instead of a custom target, which even
conflicted with ctest's own target.
Fixes #171
Not sure whether this is correct, but at least it works here.
> Fix perl testing and enable it by default

- INSTALL
The option is "WITH_GNOME2" not "WITH_GNOME", and it defaults to OFF.
> Fix WITH_GNOME2 documentation

- bindings/perl/CMakeLists.txt
- bindings/perl/src/CMakeLists.txt
This is needed to achieve (binary and source) compatibility. Unfortunately
there doesn't appear to be a more official way, even PERL_EXTRA_C_FLAGS is not
complete.
Fixes #182
> bindings: perl: Use ccflags from %Config for libproxy module compilation

- libproxy/modules/config_gnome3.cpp
Fixes: https://github.com/libproxy/libproxy/issues/191
> Use XDG_CURRENT_DESKTOP to detect GNOME desktop like systems

- src/backend/plugins/pacrunner-duktape/pacrunner-duktape.c
This PR add the (widely used?) `alert` function to each pacrunner, which directly print to stderr, prefixed with `PAC-alert:`.
Update:
Unless the `_PX_DEBUG_PACALERT` environment is set, this `alert` function will do nothing (since there is no 'browser console'), which just create the function name in pacrunner context to avoid ReferenceError while interpreting pac script.
> add alert function to pacrunners

- src/backend/px-manager.c
Fixes: https://github.com/libproxy/libproxy/issues/208
> Check for valid uri_host in ignore_ip()

- src/backend/plugins/config-gnome/config-gnome.c
- src/backend/plugins/config-kde/config-kde.c
Only check for ignore hosts if proxy are in use.
> Improve GNOME/KDE get_config() execution

- src/libproxy/proxy.h
Fixes usage of header file from C++.
Addresses one part of #226.
> Move glib2 inclusion out of c++ protection.

- src/backend/plugins/pacrunner-duktape/meson.build
Some systems need extra dependencies, such as libsocket, for networking functions.
Fixes: https://github.com/libproxy/libproxy/issues/234
> Link with libsocket where needed (#234)

- src/backend/px-manager.c
Resource leak and unchecked return values in px-manager.c
> Fix coverity findings

- src/backend/px-manager.c
Currently we have set it before each pac run, this is inefficient. Just set it immediately after download.
> Set pac data after download only

- src/backend/px-manager.c
Concurrenct access in px_manager_get_proxies_sync leads to random crashes in duktape. Limit it to one access at a time as has been done in previous releases.
> Fix race condition in px_manager_get_proxies_sync

- src/libproxy/meson.build
Since 4a4f54ca754689fb5a47dc7361e2530344ce82f5, proxy.h includes glib-gobject.h instead of gio/gio.h. We should reflect that change in the pkgconfig file.
Also, we can move the dependency from Requires to Requires.private since we only need the cflags; consumers do not need to link against libgobject.
> Update gobject dependency in pkgconfig file

- src/backend/plugins/config-env/config-env.c
Applications using libproxy can set environment variables during their runtime to influence the behaviour of libproxy. One prominent example is glib-pacrunner. Let's change it back to the flow used in 0.4 releases.
> Reread env variables in each get_config call

- src/backend/px-manager.c
Such as `udp:`.
Fixes: https://bugs.archlinux.org/task/78881
> Fix crash querying URLs without a host

- src/backend/plugins/config-windows/config-windows.c
The ProxyOverride entries are separated by semicolons, not by commas
> Use the correct separator character for Windows ProxyOverride

- meson.build
- src/backend/meson.build
- src/backend/px-manager.c
It is only used there, and the project root is added to the list of include directories last. This means that a config.h may inadvertedly be included from a completely different place when building libproxy as a subproject. The backend directory, where the generated px-backend-config.h ends up is the first include path in the list.
This commit removes config.h entirely, as the only other thing in it, the generated PACKAGE_VERSION define, is not used anywhere
> Add curl option to the generated config for backend instead

- src/backend/plugins/config-windows/config-windows.c
Windows proxy servers can be set either with or without a scheme where without implies http, and with or without a port where without implies the default port for the scheme.
Unfortunately, g_uri_parse_scheme("proxy.example.com:3128") returns "proxy.example.com" rather than NULL (while
g_uri_parse_scheme("1.2.3.4:3128") returns NULL), meaning that such proxy configurations did not get http:// prepended to them, causing e.g. GProxy to reject them.
With this change we simply search for the presence of :// in the URI instead. While a URI technically doesn't have to contain // after the scheme separator, such URIs should not occur in this context
> Windows: Detect scheme presence in proxy URLs more robustly

- src/backend/plugins/config-windows/config-windows.c
On Windows, WPAD, PAC and manual proxy settings are not mutually exclusive. They can all be set and should be tried in that order.
> Windows: Try all configured proxy resolution types

- meson.build
- meson_options.txt
In case release option is set to true, no git hooks are installed to the system.
Fixes: https://github.com/libproxy/libproxy/issues/262
> Add release option

- src/libproxy/proxy.c
- tests/libproxy-test.c
* tests: Copy pxProxyFactory correctly
The second argument to g_boxed_copy() is meant to be a pointer to the
boxed instance itself, not a pointer to a pointer to the boxed instance.
For example, `g_boxed_copy (G_TYPE_STRV, environ)` is correct (equivalent
to g_strdupv() in this case), but `g_boxed_copy (G_TYPE_STRV, &environ)`
would be incorrect. The same principle applies here.
The test passed despite this because self->pf and
&self->pf happen to both be pointer-sized, and as a result of
https://github.com/libproxy/libproxy/issues/280, the data that is pointed
to was copied byte-by-byte but not otherwise used; but this will no
longer be true when #280 is fixed, so the test needs fixing first.
* px_proxy_factory_copy: Add a new reference to the manager
Otherwise there is no guarantee that …
> Fix refcounting in px_proxy_factory_copy (#280)

- src/libproxy/libproxy.map
The ordering is not really needed - but it makes reading the file easier (if it ever gets large)
> symver: Fix symbol map to be a valid tree

- meson.build
Fails to build with:
`../src/backend/plugins/config-osx/config-osx.c:284:29: error: 'SCDynamicStoreCopyProxies' is unavailable: not available on iOS`
Which is true, it's only available on macOS 10.1+
https://developer.apple.com/documentation/systemconfiguration/1517088-scdynamicstorecopyproxies
> meson: Don't build OSX plugin on iOS

- src/backend/px-manager.c
The crash reported in https://github.com/libproxy/libproxy/issues/299 is not due to `ignore` being NULL, but it being an empty string. This can easily happen, as at least some backends create the list of "ignores" by calling `strsplit` on a delimited string. If there's a stray delimiter character in that string, the resulting vector will contain empty strings.
In `ignore_domain`, `g_strsplit` is then called (to separate port from hostname) on an empty string. `g_strsplit` has a quirk: if called on an empty string, it returns an empty array.
Then `ignore_host` is set to the first entry in that (empty) array, which will make it a NULL pointer.
Then `strlen` is called on `ignore_host`, causing the access violation and a crash.
This crash can be reproduced on Windows with libproxy 0.5.7 by …
> Properly handle empty proxy ignore entry

- src/backend/px-manager.c
This prevents further GUri API call on NULL pointer. For example, `FTP_PROXY=""` will lead into a NULL here.
> Ignore invalid proxy URL

- src/backend/px-manager.c
In cases where we enforce a specific config plugin we are leaking every other config plugin. Fix it.
> Fix memory leak using PX_FORCE_CONFIG

- src/backend/plugins/config-sysconfig/config-sysconfig.c
Some time there are white spaces in key value like key NO_PROXY, if white space is not removed, the host name can't be ignored.
> Remove white space in key value

- src/backend/plugins/config-kde/config-kde.c
- tests/config-kde-test.c
- tests/data/sample-kde-proxy-pac-without-scheme
KDE allows users to set local files without file:// scheme. Handle this case and set file:// prefix.
> kde: Support Proxy Config Script value without scheme
