libproxy/libproxy

libproxy/test/get-pac-test.cpp, libproxy/url.cpp
This uses a default block size while retrieving the PAC file if no content length was provided until retrieval is finished.
This resolves issue #40.
=> Handle PAC files without specified HTTP content length

NEWS, libproxy/CMakeLists.txt
=> Prepare for 0.4.14

libproxy/test/get-pac-test.cpp
=> get-pac-test: Fix typo

libproxy/modules/config_gnome3.cpp
=> Do not invoke extra shell to run pxgsettings

libproxy/modules/config_kde.cpp
=> config_kde: Initialize config_loc.mtime explicitly

libmodman/module_manager.cpp, libmodman/module_manager.hpp, libproxy/extension_pacrunner.cpp, libproxy/extension_pacrunner.hpp, libproxy/modules/config_gnome3.cpp, libproxy/modules/ignore_ip.cpp, libproxy/modules/pacrunner_mozjs.cpp, libproxy/proxy.cpp, libproxy/test/url-encode.cpp, libproxy/test/url-test.cpp, libproxy/url.cpp, libproxy/url.hpp
* pass strings by const & instead of copy
* Search single chars as chars and not as strings
=> Small performance improvements

libproxy/url.cpp
This function processes network input. It's semi-trusted, because the
PAC ought to be trusted. But we still shouldn't allow it to control how
far we recurse. A malicious PAC can cause us to overflow the stack by
sending a sufficiently-long line without any '\n' character.
Also, this function failed to properly handle EINTR, so let's fix that
too, for good measure.
Fixes #134
=> Rewrite url::recvline to be nonrecursive

bindings/python/libproxy.py
In Python 3, strings are Unicode (UTF-16 or UTF-32 depending on build
options), and are passed to ctypes function wrappers as such.
Convert the input URL to a bytestring for processing by libproxy, and
convert the results back into (Unicode) strings by decoding them.
From the pacrunner_webkit module, it appears that libproxy expects
strings to be in UTF-8 (like GLib/GTK), so use that encoding for
bytestrings.
---
I'm not sure this is the right solution to #65, but it's certainly an improvement.
=> python: Convert URLs to/from UTF-8 under Python 3

libproxy/url.cpp
Include cerrno header for errno and EINTR.
=> Include cerrno

libproxy/modules/config_kde.cpp
Instead of using the deprecated `kf5-config`, compute the list of config file
locations ourselves, according to the FDO basedir-spec.
It turned out to require less code than I expected, so yay.
See discussion in https://github.com/libproxy/libproxy/pull/166
At least here it works just like it did before, the list of locations is the same here.
This treats an empty `$HOME` variable like if it was unset, but I hope that's not an issue in practice.
@apachelogger @mss: Please have a look and feel free to test it as well.
=> config_kde: Compute list of config file locations ourselves

libproxy/cmake/modules/pacrunner_duktape.cmk, libproxy/modules/pacrunner_duktape.cpp
Related with https://github.com/libproxy/libproxy/issues/193
This PR enables the usage of Ducktape in Windows systems
=> Enable the use of ducktape in Windows systems

libproxy/cmake/pkgconfig.cmk
Closes #188 using @jiegec's patch in NixOS/nixpkgs#184328.
=> Fix build on macOS

src/backend/plugins/pacrunner-duktape/pacrunner-duktape.c
=> Fix build on NetBSD.

meson.build, src/backend/meson.build
Fixes: https://github.com/libproxy/libproxy/issues/222
=> Install libpxbackend into pkglibdir

src/backend/px-manager.c, tests/px-manager-helper.c
Fixes: https://github.com/libproxy/libproxy/issues/224
=> Enforce online state for tests

src/libproxy/meson.build
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=2209173
=> Fix libproxy rpath

src/backend/plugins/config-windows/config-windows.c
- Handle proxy URLs being provided with a scheme
- Don't assume that target URL scheme == proxy scheme
- Use proxy provided without a scheme specifier for all target URL schemes
- Free memory allocated for hash table keys and values
From testing, this is much more in line with how Edge and the .NET [System.Net.WebProxy](https://learn.microsoft.com/en-us/dotnet/api/system.net.webproxy?view=netframework-4.8.1) works
=> Improve handling of Windows proxy settings:

src/backend/px-manager.c
When discovering a PAC URL through WPAD, libproxy would download the file, but never call `set_pac()` on the PAC Runner interface, unlike in the case with an explicitly configured PAC URL. This would cause the PAC Runner implementation to just return an empty string from `run()`
=> Fix broken WPAD proxy resolution

src/backend/px-manager.c
Release curl handle in dispose.
=> Cleanup curl

meson.build
Fixes: https://github.com/libproxy/libproxy/issues/285
=> Fix crash during unload

src/backend/px-manager.c
Fixes: https://github.com/libproxy/libproxy/issues/299
=> Handle empty ignore settings

src/backend/px-manager.c, tests/data/px-manager-sample.pac, tests/px-manager-test.c
Fixes: https://github.com/libproxy/libproxy/issues/304
=> Add support for direct keyword in PAC

src/backend/plugins/config-kde/config-kde.c
Fixes: https://github.com/libproxy/libproxy/issues/311
=> kde: Add ReversedException support

docs/build-steps.md
Fix glib package name and add gsettings-desktop-schemas.
Fixes: https://github.com/libproxy/libproxy/issues/315
=> Update msys2 build steps

src/backend/plugins/config-gnome/config-gnome.c, tests/config-gnome-test.c
Fixes: https://github.com/libproxy/libproxy/issues/323
=> Add MATE and Cinnamon check to gnome plugin
